version: 0.0
os: linux
files:
  - source: /
    destination: /web/
hooks:
  AfterInstall:
    - location: scripts/mkdir.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_flask.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_flask1.sh
      timeout: 300
      runas: ec2-user


      