version: 0.2
run-as: root
env:
  shell: bash
phases:
  install:
    commands:
        - python --version
        - yum update -y
        - pip3 install Flask
  build:
    commands:
      - echo Build started on `date`
      - export AWS_ACCESS_KEY=AKIAXRXSVCDYRP6RGSPK
      - export AWS_SECRET_ACCESS_KEY=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
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
